import type { IPhoneModel } from './iosTypes';

export const iPhoneModels: IPhoneModel[] = [
  { name: 'iPhone 3G', maxOS: '4', screen: { width: 320, height: 480 } },
  { name: 'iPhone 3GS', maxOS: '6', screen: { width: 320, height: 480 } },
  { name: 'iPhone 4', maxOS: '7', screen: { width: 320, height: 480 } },
  { name: 'iPhone 4S', maxOS: '9', screen: { width: 320, height: 480 } },
  { name: 'iPhone 5', maxOS: '10', screen: { width: 320, height: 568 } },
  { name: 'iPhone 5c', maxOS: '10', screen: { width: 320, height: 568 } },
  { name: 'iPhone 5s', maxOS: '12', screen: { width: 320, height: 568 } },
  { name: 'iPhone 6', maxOS: '15', screen: { width: 375, height: 667 } },
  { name: 'iPhone 6 Plus', maxOS: '15', screen: { width: 414, height: 736 } },
  { name: 'iPhone 6s', maxOS: '15', screen: { width: 375, height: 667 } },
  { name: 'iPhone 6s Plus', maxOS: '15', screen: { width: 414, height: 736 } },
  { name: 'iPhone SE (1st generation)', maxOS: '15', screen: { width: 320, height: 568 } },
  { name: 'iPhone 7', maxOS: '15', screen: { width: 375, height: 667 } },
  { name: 'iPhone 7 Plus', maxOS: '15', screen: { width: 414, height: 736 } },
  { name: 'iPhone 8', maxOS: '16', screen: { width: 375, height: 667 } },
  { name: 'iPhone 8 Plus', maxOS: '16', screen: { width: 414, height: 736 } },
  { name: 'iPhone X', maxOS: '16', screen: { width: 375, height: 812 } },
  { name: 'iPhone XR', maxOS: 'supported', screen: { width: 414, height: 896 } },
  { name: 'iPhone XS', maxOS: 'supported', screen: { width: 375, height: 812 } },
  { name: 'iPhone XS Max', maxOS: 'supported', screen: { width: 414, height: 896 } },
  { name: 'iPhone SE (2nd generation)', maxOS: 'supported', screen: { width: 375, height: 667 } },
  { name: 'iPhone 11', maxOS: 'supported', screen: { width: 414, height: 896 } },
  { name: 'iPhone 11 Pro', maxOS: 'supported', screen: { width: 375, height: 812 } },
  { name: 'iPhone 11 Pro Max', maxOS: 'supported', screen: { width: 414, height: 896 } },
  { name: 'iPhone 12', maxOS: 'supported', screen: { width: 390, height: 844 } },
  { name: 'iPhone 12 mini', maxOS: 'supported', screen: { width: 375, height: 812 } },
  { name: 'iPhone 12 Pro', maxOS: 'supported', screen: { width: 390, height: 844 } },
  { name: 'iPhone 12 Pro Max', maxOS: 'supported', screen: { width: 428, height: 926 } },
  { name: 'iPhone 13', maxOS: 'supported', screen: { width: 390, height: 844 } },
  { name: 'iPhone 13 mini', maxOS: 'supported', screen: { width: 375, height: 812 } },
  { name: 'iPhone 13 Pro', maxOS: 'supported', screen: { width: 390, height: 844 } },
  { name: 'iPhone 13 Pro Max', maxOS: 'supported', screen: { width: 428, height: 926 } },
  { name: 'iPhone 14', maxOS: 'supported', screen: { width: 390, height: 844 } },
  { name: 'iPhone 14 Plus', maxOS: 'supported', screen: { width: 428, height: 926 } },
  { name: 'iPhone 14 Pro', maxOS: 'supported', screen: { width: 390, height: 932 } },
  { name: 'iPhone 14 Pro Max', maxOS: 'supported', screen: { width: 430, height: 932 } },
  { name: 'iPhone 15', maxOS: 'supported', screen: { width: 393, height: 852 } },
  { name: 'iPhone 15 Plus', maxOS: 'supported', screen: { width: 430, height: 932 } },
  { name: 'iPhone 15 Pro', maxOS: 'supported', screen: { width: 393, height: 852 } },
  { name: 'iPhone 15 Pro Max', maxOS: 'supported', screen: { width: 430, height: 932 } },
  { name: 'iPhone 16', maxOS: 'supported', screen: { width: 393, height: 852 } },
  { name: 'iPhone 16 Plus', maxOS: 'supported', screen: { width: 430, height: 932 } },
  { name: 'iPhone 16 Pro', maxOS: 'supported', screen: { width: 402, height: 874 } },
  { name: 'iPhone 16 Pro Max', maxOS: 'supported', screen: { width: 440, height: 956 } },
  { name: 'iPhone 16e', maxOS: 'supported', screen: { width: 390, height: 844 } },
];
